In [1]:
import pandas as pd

In [2]:
# importing raw data
df_sales = pd.read_csv('data/king_county_house_sales.csv', sep = ';')

In [3]:
df_sales.head()

         date     price    house_id  id
0  2014-10-13  221900.0  7129300520   1
1  2014-12-09  538000.0  6414100192   2
2  2015-02-25  180000.0  5631500400   3
3  2014-12-09  604000.0  2487200875   4
4  2015-02-18  510000.0  1954400510   5

In [4]:
df_sales.columns

Index(['date', 'price', 'house_id', 'id'], dtype='object')

In [5]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      21597 non-null  object
 1   price     21597 non-null  float64
 2   house_id  21597 non-null  int64
 3   id        21597 non-null  int64
dtypes: float64(1), int64(2), object(1)
memory usage: 675.0+ KB

In [6]:
df_sales.duplicated().value_counts()

False    21597
Name: count, dtype: int64

In [16]:
df_sales.house_id.duplicated().value_counts()

house_id
False    21420
True       177
Name: count, dtype: int64

In [8]:
df_sales.price.describe()

count    2.159700e+04
mean     5.402966e+05
std      3.673681e+05
min      7.800000e+04
25%      3.220000e+05
50%      4.500000e+05
75%      6.450000e+05
max      7.700000e+06
Name: price, dtype: float64

In [ ]:
type(df_sales['date'][0])

str

In [11]:
df_sales['date']

0        2014-10-13
1        2014-12-09
2        2015-02-25
3        2014-12-09
4        2015-02-18
            ...
21592    2014-05-21
21593    2015-02-23
21594    2014-06-23
21595    2015-01-16
21596    2014-10-15
Name: date, Length: 21597, dtype: object

-> bleibt nur den Datentyp für Spalte date zu date zu ändern und price sollte immer auf 2 Stellen nachd dem Komma angezeigt werden

In [12]:
df_sales['date'] = pd.to_datetime(df_sales['date'], format='%Y-%m-%d')
df_sales['date']

0       2014-10-13
1       2014-12-09
2       2015-02-25
3       2014-12-09
4       2015-02-18
           ...
21592   2014-05-21
21593   2015-02-23
21594   2014-06-23
21595   2015-01-16
21596   2014-10-15
Name: date, Length: 21597, dtype: datetime64[ns]

In [14]:
df_sales['price'] = df_sales.price.round(3)
df_sales.head()

        date     price    house_id  id
0 2014-10-13  221900.0  7129300520   1
1 2014-12-09  538000.0  6414100192   2
2 2015-02-25  180000.0  5631500400   3
3 2014-12-09  604000.0  2487200875   4
4 2015-02-18  510000.0  1954400510   5

In [15]:
df_sales.to_csv('data/clean_king_county_house_sales.csv',index=False, sep=';')